In [1]:
import numpy as np
import pandas as pd

## Question 1 ##

In [52]:
pd.__version__

'1.4.2'

### Answer: 1.4.2 ###

In [6]:
df = pd.read_csv('data_hmw.csv')

## Question 2 ##

In [51]:
len(df.columns)

10

### Answer: 10 ###

## Question 3 ##

In [50]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

### Answer: total_bedrooms ###

## Question 4 ##

In [49]:
df['ocean_proximity'].nunique()

5

### Answer: 5 ###

## Question 5 ##

In [29]:
df2 = df[df['ocean_proximity'] == 'NEAR BAY']

In [32]:
df2['median_house_value'].mean().round()

259212.0

### Answer: 259212.0 ###

## Question 6 ##

In [41]:
mean_total_bedrooms = df['total_bedrooms'].mean()

In [37]:
df3 = df.fillna(mean_total_bedrooms)

In [40]:
mean_total_bedrooms_filled = df3['total_bedrooms'].mean()

In [43]:
mean_total_bedrooms

537.8705525375618

In [44]:
mean_total_bedrooms_filled 

537.8705525375617

In [45]:
mean_total_bedrooms.round(3)

537.871

In [46]:
mean_total_bedrooms_filled .round(3)

537.871

In [47]:
mean_total_bedrooms.round(3) != mean_total_bedrooms_filled.round(3)

False

### Answer: NO ###

## Question 7 ##

In [61]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [64]:
df_island = df[df['ocean_proximity'] == 'ISLAND']

In [65]:
df_island

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [67]:
df_island_filtered = df_island[['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [69]:
df_island_filtered

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [71]:
X = df_island_filtered.values

In [72]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [85]:
X_trs = X.T

In [86]:
X_trs

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [103]:
XTX = X_trs.dot(X)

In [104]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [105]:
XTX_inv = np.linalg.inv(XTX)

In [106]:
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [92]:
y = np.array([950, 1300, 800, 1000, 1300])

In [93]:
y

array([ 950, 1300,  800, 1000, 1300])

In [108]:
w = (XTX_inv.dot(X_trs).dot(y))

In [114]:
w[-1].round(4)

5.6992

### Answer: 5.6992 ###